# 
# Copyright (c) 2022 Amazon.com, Inc. or its affiliates.  All rights reserved.
# 
# PROPRIETARY/CONFIDENTIAL.  USE IS SUBJECT TO LICENSE TERMS.
# 
schema-version = 1

[package]
title = "Basic UI React Native Application"
version = "0.1.0"
id = "com.amazon.kepleraccedo"

[components]
[[components.interactive]]
id = "com.amazon.kepleraccedo.main"
stem-family = "com.amazon.family.runtime.keplerscript.0.67"
launch-type = "singleton"